# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0002_auto_20160411_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='client',
        ),
    ]
