# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0003_remove_key_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
